eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8381
spring:
  application:
    name: spring-demo-service-ribbon

management:
  endpoints:
    web:
      exposure:
        include: '*'